on:
  push:
  pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Setup
            run: sudo apt-get update && sudo apt-get install --no-install-recommends -y biber latexmk lmodern texlive-bibtex-extra texlive-latex-extra texlive-science
          - name: Checkout
            uses: actions/checkout@v2
          - name: Keep Racket edition
            run: sed -i 's|\\def\\edition{0}|\\def\\edition{0}|g' book.tex
          - name: Build PDF
            run: make
          - name: Release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
              files: book.pdf
